# Generated by https://quicktype.io

from typing import List
from pydantic_yaml import YamlModel


class IndividualUser(YamlModel):
    username: str
    groups: List[str]


class IndividualUsersModel(YamlModel):
    users: List[IndividualUser]
