org                      = "csi"
app                      = "htr"
env                      = "tst"
shared_credentials_files = "~/.aws/.csi/credentials"
shared_config_files      = "~/.aws/.csi/config"
region                   = "eu-west-1"
profile                  = "rtr_adm"
