name: "Build & Publish tpl-gen to GH packages"

on:
  repository_dispatch:
    types: build-and-publish-imgs
  push:
    branches:
      - dev
      - tst
      - prd
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:

      - name: set envs
        run: |
          echo UID=$(id -u) >> $GITHUB_ENV
          echo GID=$(id -g) >> $GITHUB_ENV
          echo PRODUCT=tpl-gen >> $GITHUB_ENV
          echo CUR_BRANCH=${GITHUB_REF##*/} >> $GITHUB_ENV
          echo RELEASE_VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CUR_BRANCH }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tpl-gen Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./src/docker/tpl-gen/Dockerfile.x86_64
          build-args: |
            UID=${{ env.UID }}
            GID=${{ env.GID }}
            PRODUCT=${{ env.PRODUCT }}
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/${{ env.PRODUCT }}-tpl-gen-img:${{ env.RELEASE_VERSION }}
